#!/bin/sh
echo "You are about to commit" $(git diff --cached --name-only --diff-filter=ACM)
echo "to" $(git branch --show-current)
echo "I'm sending email to your boss!"

#aws ses send-raw-email --cli-binary-format raw-in-base64-out --region us-east-1 --raw-message "{ \"Data\": \"From: name@gmail.com\nTo: name@gmail.com\nSubject: Commit report\n\nNew commit.\n\n\" }"

sudo echo "To: piotrpit.uek@gmail.com
From: piotrpit.uek@gmail.com
Subject: Sent from a terminal!

Your content goes here. Lorem ipsum dolor sit amet, consectetur adipisicing.
(Notice the blank space between the subject and the body.)" > mail.txt

sudo ssmtp piotrpit.uek@gmail.com < mail.txt
sudo rm mail.txt

